language: cpp
sudo: true
dist: trusty
addons:
  apt:
    sources: &1
    - ubuntu-toolchain-r-test
    - sourceline: ppa:kalakris/cmake
    - sourceline: ppa:adrozdoff/cmake
    - sourceline: ppa:h-rayflood/llvm
    packages: &2
    - cmake
    - libgmp-dev
    - libgoogle-perftools-dev
cache:
  apt: true
  directories:
  - "$HOME/lean"
matrix:
  include:
  # - os: linux
  #   dist: precise
  #   env: CMAKE_CXX_COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release TARGET=build/lean-3.1.1-linux.tar.gz
  #     UPLOAD=ON STATIC=ON
  - os: linux
    addons: &4
      apt:
        sources: *1
        packages:
        - *2
        - g++-4.9
        - clang-3.4
    env: CMAKE_CXX_COMPILER=clang++-3.4 CMAKE_BUILD_TYPE=Release TCMALLOC=ON
  - os: linux
    addons: &3
      apt:
        sources: *1
        packages:
        - *2
        - g++-6
        - gcc-6
    env: CMAKE_CXX_COMPILER=g++-6 CMAKE_BUILD_TYPE=Release TCMALLOC=ON
  - os: linux
    addons: *3
    env: CMAKE_CXX_COMPILER=g++-6 CMAKE_BUILD_TYPE=Release
  - addons: *3
    os: linux
    env: CMAKE_CXX_COMPILER=g++-6 CMAKE_BUILD_TYPE=Release LATEST=true
  - os: linux
    addons: *3
    env: CMAKE_CXX_COMPILER=g++-6 CMAKE_BUILD_TYPE=Release MULTI_THREAD=OFF
  - os: osx
    addons: &4
    env: CMAKE_CXX_COMPILER=clang++ CMAKE_BUILD_TYPE=Release TARGET=build/lean-3.1.1-darwin.zip
      UPLOAD=ON PACKAGE=TRUE
  allow_failures:
  - env: CMAKE_CXX_COMPILER=g++-6 CMAKE_BUILD_TYPE=Release LATEST=true
before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install gcc && brew install gmp; fi
- mkdir -p $HOME/lean
- pushd $HOME/lean
- ls .git || (git init && git remote add origin https://github.com/leanprover/lean.git)
- git fetch origin
- |
   if [[ $LATEST == true ]]
   then
     git pull origin master
   else
     git checkout 5efa1b829cfb4df5e5f4ddaec96c6d8707d24236
   fi
- mkdir -p build
- cd build
- if [[ $TCMALLOC != ON ]]; then TCMALLOC=OFF; fi
- if [[ $STATIC != ON ]]; then STATIC=OFF; fi
- if [[ $MULTI_THREAD != OFF ]]; then MULTI_THREAD=ON; fi
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
  -DTCMALLOC=$TCMALLOC -DMULTI_THREAD=$MULTI_THREAD -DSTATIC=$STATIC -DLEAN_EXTRA_MAKE_OPTS=$LEAN_EXTRA_MAKE_OPTS
  ../src || exit
- make -j2 || exit
- export PATH=$HOME/lean/bin:$PATH
- popd
script:
- lean -v || echo "success"
- lean --path
- export LEAN_PATH=`pwd`:`pwd`/lean-lib:$HOME/lean/bin/../lib/lean/library:$HOME/lean/bin/../library
- lean --path
- echo $LEAN_PATH
# - git submodule sync
- leanpkg configure
- leanpkg build -- --trust=2
notifications:
  slack:
    rooms:
      secure: ToqNpQO5kipHcuV9zrUodENHyuIiizuX01rdRjvSRGxw9Ad1JbvAnm4wUZhEl+ikgUDLXBwbngWj7uxLUCXiWn84hLU/WGqfKWre0KBvrpLXNDfwvHhxPZsIy0bmWqdQ2di86Fzd6dcNitQT5SXn6ydpTTNqDth/MGSljEEaqCJqdEEOZWlGJ4SoQ3ujf5fk5gjojg76FJ1Ua/VlnS/aziLveECgk4webztjxPgGYz6KlSF7vTinO9LXUObfOfy4M0MPze/QdxtHVdlnpCggASfdvx7js//9BP/Ap2tKK2mp5eQ66hqzXHCyzuuOpL7u3jeSNGkI5kZgCQiFPZzT+Fxc7I1DdRJ5S/guG39MY/2H2Z5vahMFWuVkkrEgfyVf+b85rGYMPSRrGV8PDLLiaxiwjec121xpmbnpuLfL4ZZQ1/+Oct8jUordbbS9ZIr0HCcFckR4GVhA4iDgl6NErBfpAKhs8jhBKAHicJpgQm6LborWdSiOs24TBwOI4e1xvllNaJHzUfM9yhXVc1Y0hQr88anwtBh7VCvk3a2HchVGo684WwZcoJn3y2MGVw6U3ecOBPnrAnG4nTKD2WlpOqmr0wEzxxTRhW2Bm3Djgn2p8xsNgwcQigYrE2p89nrgcd7Xv3gxNW/Qe/dp3bTEgdbDo8fFhsO+ZB940SvDTos=
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGFtaW5iJTNBbWF0cml4Lm9yZy8lMjF4eUlwdkJPc3FYWWhVRmdWWVclM0FtYXRyaXgub3Jn"
    on_success: always  # always|never|change
    on_failure: always
    on_start: never
